export { default as Home} from './home/Home'
export { default as About} from './aboutus/About'
export { default as Cont} from './contactus/Cont'
export { default as Signup} from './signup/Signup'
export { default as Login} from './login/Login'